on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run deploy.sh script
        run: ./.github/scripts/deploy.sh
        shell: bash
